## Pandas
Pandas is a software library written for the Python programming language for data manipulation and analysis.

### Series
A series is a 1D labeled array, capable of holding any data type. The axis labels are collectively called index.

In [2]:
import pandas as pd
import numpy as np

In [3]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10, 2:20, 3:30}

In [4]:
pd.Series(my_list) # The labels by default start from 0

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
# Series can be created from series as well
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
# While creating series from a dictionary, the keys become the label
pd.Series(d)

1    10
2    20
3    30
dtype: int64

#### Dataframe
A Pandas DataFrame is a two-dimensional table that stores data in rows and columns

##### Creating a Dataframe

In [40]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
# When we don't provide keys, it marks each column with a number
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [42]:
# We can define the column name as follows
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Selection of Columns

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [45]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

##### Creating a new Column

In [46]:
# When adding a new column, we need to provide the correct number of data
df2["Designation"] = ["Doctor", "Engineer", "Doctor", "Engineer"]

In [47]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

##### Removing a Row/ Column

In [48]:
df2.drop("Designation", axis=1) # By default the axis is zero, so we need to specify it.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
# Drop (unless specified) does not change the actual dataframe
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [50]:
# If we want to do so, we can use inplace=True
df2.drop("Designation", axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000