## Pandas
Pandas is a software library written for the Python programming language for data manipulation and analysis.

### Series
A series is a 1D labeled array, capable of holding any data type. The axis labels are collectively called index.

In [85]:
import pandas as pd
import numpy as np

In [86]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10, 2:20, 3:30}

In [87]:
pd.Series(my_list) # The labels by default start from 0

0    10
1    20
2    30
dtype: int64

In [88]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [89]:
# Series can be created from series as well
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [90]:
# While creating series from a dictionary, the keys become the label
pd.Series(d)

1    10
2    20
3    30
dtype: int64

#### Dataframe
A Pandas DataFrame is a two-dimensional table that stores data in rows and columns

##### Creating a Dataframe

In [91]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [92]:
# When we don't provide keys, it marks each column with a number
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [93]:
# We can define the column name as follows
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Selection of Columns

In [94]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [95]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [96]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

##### Creating a new Column

In [97]:
# When adding a new column, we need to provide the correct number of data
df2["Designation"] = ["Doctor", "Engineer", "Doctor", "Engineer"]

In [98]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

##### Removing a Row/ Column

In [99]:
df2.drop("Designation", axis=1) # By default the axis is zero, so we need to specify it.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [100]:
# Drop (unless specified) does not change the actual dataframe
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [101]:
# If we want to do so, we can use inplace=True
df2.drop("Designation", axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [102]:
# We can also remove the rows
df2.drop([0, 1], axis=0)

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [103]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [104]:
# Accessing rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [105]:
# Accessing multiple rows
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [106]:
# Integer based location
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

##### Selecting Subsets of Rows and Columns

In [107]:
df2.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [108]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

##### Conditional Selection

In [109]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [110]:
# Get rows with age above 30
# Done in a similar way to numpy
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [111]:
# Get rows with age above 30 and where city is paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

#### Handling Missing Data

##### Finding Missing Data

In [112]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [113]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [114]:
# Check if some values are none
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [115]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [116]:
# Tells you which columns have null values
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

##### Remove Missing Numbers

In [117]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [118]:
# Using dropna() we can remove rows whcih have null values
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [119]:
# using thresh in dropna()
# thresh specifies how many non-null values must exist and then remove
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [120]:
# Using fillna() allows you to fill values at null locations
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [121]:
# We can define what we want in place of null in a particular column
values={'A':0, 'B': 100, 'C':300, 'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [122]:
# But to persist these changes in the original df, we have to use inplace=True
df.fillna(0, inplace=True)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [123]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [124]:
# We can replace null values with mean
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

#### Merging, Joining and Concatenation

In [125]:
# DataFrame 1: Employee Information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [126]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [127]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [128]:
# Only the key that is common among both will be used to merge (only ids that exist in 
# both will be visible)
pd.merge(employees, salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [129]:
# We can specifically define which column to merge on as well
pd.merge(employees, salaries, on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [130]:
# we can also define 'how' which by default is inner
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [131]:
# we can use outer join to get all the values - with null for those which do not exist
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [132]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [133]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

##### Concatenation of 2 Dataframes

In [134]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [135]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [136]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [137]:
# If no axis is defined, concatenation happens column wise
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [138]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

##### Joining 2 Dataframes

In [139]:
# First Dataframe
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [140]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [141]:
df2

   score
2     85
3     90
4     75

In [142]:
# By default, it is inner join
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [143]:
# We can specify the type of join as follows
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

#### Group By and Aggregation

In [144]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [145]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [146]:
# Group by Category and Calculate the sum of sales
gb = df.groupby('Category') # This is an object
# We can view it by looping
for i in gb:
    print(i)

('A',   Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07)
('B',   Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08)

In [147]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [148]:
# Group by store and calculate sum of sales
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [149]:
# Group by multiple columns
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

##### Aggregation 
An aggregate in Pandas is an operation that reduces multiple values down to a single summary statistic, such as a sum, mean, minimum, maximum, or count.

In [150]:
df['Sales'].mean()

np.float64(187.5)

In [151]:
df['Sales'].median()

np.float64(190.0)

In [152]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [153]:
# We can get multiple values at once as well
df['Sales'].agg(['mean', 'median', 'min','max'])

mean      187.5
median    190.0
min       100.0
max       300.0
Name: Sales, dtype: float64

#### Pivot Tables

In [154]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    259     43   John  January      Q1
1  2023-01-02       B   West    413     33   Mary  January      Q1
2  2023-01-03       C  North    446     49    Bob  January      Q1
3  2023-01-04       D  South    182     54  Alice  January      Q1
4  2023-01-05       A   East    163     13   John  January      Q1
5  2023-01-06       B   West    494     59   Mary  January      Q1
6  2023-01-07       C  North    989     27    Bob  January      Q1
7  2023-01-08       D  South    462     18  Alice  January      Q1
8  2023-01-09       A   East    553     76   John  January      Q1
9  2023-01-10       B   West    666     99   Mary  January      Q1
10 2023-01-11       C  North    140     80    Bob  January      Q1
11 2023-01-12       D  South    331     70  Alice  January      Q1
12 2023-01-13       A   East    587     85   John  January      Q1
13 2023-01-14       B   West    611     57   Mary  January      Q1
14 2023-01-15       C  North    707     79    Bob  January      Q1
15 2023-01-16       D  South    561     64  Alice  January      Q1
16 2023-01-17       A   East    611     94   John  January      Q1
17 2023-01-18       B   West    816     33   Mary  January      Q1
18 2023-01-19       C  North    587     14    Bob  January      Q1
19 2023-01-20       D  South    474     77  Alice  January      Q1

In [155]:
# pd.pivot_table(
#     df,
#     values=X,
#     index=Y,
#     columns=Z,
#     aggfunc=W
# )
# Read it as:
# "Take column X, group it by Y, split it by Z, and perform calculation W."
pd.pivot_table(df, values="Sales", index="Region", columns="Product")

Product      A      B      C      D
Region
East     434.6    NaN    NaN    NaN
North      NaN    NaN  573.8    NaN
South      NaN    NaN    NaN  402.0
West       NaN  600.0    NaN    NaN

In [156]:
# We can define the aggregation function as well, which is mean by default
pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc="median")

Product      A      B      C      D
Region
East     553.0    NaN    NaN    NaN
North      NaN    NaN  587.0    NaN
South      NaN    NaN    NaN  462.0
West       NaN  611.0    NaN    NaN

In [157]:
pd.pivot_table(df, values=["Sales", "Units"], index="Region", columns="Product", aggfunc="median")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     553.0    NaN    NaN    NaN  76.0   NaN   NaN   NaN
North      NaN    NaN  587.0    NaN   NaN   NaN  49.0   NaN
South      NaN    NaN    NaN  462.0   NaN   NaN   NaN  64.0
West       NaN  611.0    NaN    NaN   NaN  57.0   NaN   NaN

In [158]:
# Always take numeric values in pivot table since you are performing aggregations

#### Cross Tabs
Crosstab is very similar to a pivot table, but it's mainly used to count how often combinations of categories occur.

In [160]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

#### Operations

In [161]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [162]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [163]:
df1.shape

(5, 3)

In [164]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [166]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [167]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [168]:
# Broadcasting
df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### Applying Functions on DataFrames

In [170]:
def square(x):
    return x**2

In [171]:
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [174]:
# If we mention a new column - it will get created 
df1["D"] = df1["B"].apply(square)

In [175]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500